### ISSUE TITLE
Decide what licence to use for the format

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-format#1]
What shall we use? Probably something quite relaxed, right? Maybe the same licence that we already use for the APIs?

**Comment by tobiaszuercher** [comment]
i'd just stick to the licence

**Comment by bruderol** [comment]
Some very relaxed licence. at least same relaxed as the API, if not even more relaxed.

**Comment by bruderol** [comment]
we agreed on GPL Lesser
