### ISSUE TITLE
Implement Scenarioo-Java Writer to write all entities from java

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-format#10]

**Comment by dola** [comment]
http://www.baeldung.com/jackson-deserialization
http://stackoverflow.com/questions/11106053/how-to-serialize-a-map-as-list-using-jackson

**Comment by bruderol** [comment]
initial reference implementation for java considered feature complete.

@dola, @tobiaszuercher and everybody:
you can review if you want
