### ISSUE TITLE
Choose technologies to use

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-format#26]
What technologies will we use?
- Jackson for Java
- TV4 for Javascript and validation of json schema in general
- ... to be defined ...
- Guava for Condition checks in Java?

**Comment by bruderol** [comment]
@dola @tobiaszuercher 

what do we use??

for Java: I propose to use Jackson

**Comment by dola** [comment]
Schema Validation:
http://json-schema.org/implementations.html
